server:
  port: 8400
spring:
  application:
    name: ms-posts
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/posts
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwksUri: http://localhost:8200/oauth2/jwks